version: '2'

services: 
    migu-api:
        image: "migu-api:latest"
        build: ./
        
        ports: 
            - "3500:3500"
        networks: 
            - mynet
networks: 
    mynet:
        external: true